### ISSUE TITLE
webbify not documented

### ISSUE THREAD

**Issue by cfjedimaster** [ibm-functions/composer#14]
Typing `fsh` and the help screen does not mention webbify. Also, if you `fsh webbify`, check out the result:

"Please select an action, either via "webbify <action>", or by opening it in the sidecar"

That sounds like maybe it was meant for UI, not the CLI.

**Comment by cfjedimaster** [comment]
Also note it isn't in the graphical help.

**Comment by rabbah** [comment]
Issue moved to [ibm-functions/shell #38](https://github.com/ibm-functions/shell/issues/38) via [**ZenHub**](https://www.zenhub.com/)
