### ISSUE TITLE
Consider slimming the header

### ISSUE THREAD

**Issue by cfjedimaster** [ibm-functions/composer#15]
This is probably a bit picky, but I figured I'd post it to see what other's thought. Look at the amount of space used for the header here:

![image](https://user-images.githubusercontent.com/393660/31382671-12889b6e-ad7e-11e7-926d-bbbe388476e4.png)

Maybe it should be slimmed down a bit? I don't plan on doing "stuff" in the shell, but I know some folks will, so having more space to enter commands and such may be nice.

**Comment by rabbah** [comment]
The footer seems to have expanded also in recent releases.

**Comment by rabbah** [comment]
Issue moved to [ibm-functions/shell #37](https://github.com/ibm-functions/shell/issues/37) via [**ZenHub**](https://www.zenhub.com/)
