### ISSUE TITLE
Socket hang up during long-running sequences

### ISSUE THREAD

**Issue by epatters** [ibm-functions/composer#24]
I have a composer sequence that invokes a long-running (atomic) action. The action takes about 25s to run. After about 10s, I get the error

```
{
    "code": 400,
    "error": "Failed to invoke action [my long-running action]: Unknown Error From API: socket hang up"
}
```

from the sequence app. (After another 15s, the action completes successfully but it's too late for the sequence.)

I've seen this problem before but it's gotten much worse within the past week. My compositions are now unusable.

On a Slack channel I received the advice to use the `$blocking: true` argument to work around a related issue with long-running nested compositions (returning a session ID instead of the result) but that seems to be a separate problem and the workaround does not help here.

**Comment by tardieu** [comment]
I will try to reproduce. This has indeed nothing to do with `$blocking`.

**Comment by starpit** [comment]
i'm wondering if this is related to connection-open timeouts. the openwhisk npm is using the default open timeout from needle: 10 seconds. if i increase this, the socket hangup issues seem to be reduced, in my initial testing.

i'm not sure why, sometimes, it takes more than 10 seconds to establish a connection...

**Comment by starpit** [comment]
1.3.368 has a workaround for this.

the core issue is here: https://github.com/tomas/needle/issues/229

**Comment by epatters** [comment]
I can happily report that this issue seems to be fixed now that the upstream fixes are live on Bluemix. Thank you @tardieu and @starpit for your help!
