### ISSUE TITLE
Example code typo in retain.js app creation

### ISSUE THREAD

**Issue by devgeeks** [ibm-functions/composer#26]
Under [Nesting and Forwarding](https://github.com/ibm-functions/composer/blob/master/docs/README.md#nesting-and-forwarding) in `docs/README.md`:

```bash
$ fsh app create try @demos/retain.js
```
Should be

```bash
$ fsh app create retain @demos/retain.js
```

**Comment by rabbah** [comment]
Thanks! We’d love a pull request :)

**Comment by devgeeks** [comment]
I mean... I am happy to do so, but it's a lot to ask of most people to sign an ICLA and make a PR for a one-line change in a README. ;)

**Comment by rabbah** [comment]
:) fair
