### ISSUE TITLE
task from file (or url) supoprt

### ISSUE THREAD

**Issue by rabbah** [ibm-functions/composer#3]
apps currently require separately deploying referenced actions, but this is inconvenient and error prone:

1. actions could get out of sync with the app when it's compiled
2. if actions reside in a package, naming them has to be kept in sync with the deployment script
3. you need a scripting to deploy the actions and the app (where we should be striving to eschew programming by bash)

one approach is to use a `taskFromFile` combinator using `npm openwhisk`, but this adds a wrinkle because the underlying API in `npm openwhisk` is promise based, and hence the composer must handle the asynchrony. So a better approach is to treat the `taskFromFile` combinator as a plan generator, which can run under a seperate life cycle for the composition (i.e., not necessarily the `compile` step), and which can therefore automate the deployment, and later, undeployment.

a nice feature of inline task from file is that the name of the action is transparent to the composition: one does not have to name the action in one place (deployment) and then reference it later in the composition, where one could make a mistake.

**Comment by tardieu** [comment]
Implemented in v2. Loading action code from file is synchronous. No issue there. Deploy is asynchronous. Deploy can handle a composition and the referenced actions (or compositions).
