### ISSUE TITLE
Session list pagination is broken

### ISSUE THREAD

**Issue by cfjedimaster** [ibm-functions/composer#30]
When I run `session list` in the shell and click the right arrow in the pagination, I see 2 more sessions and that's it. So I thought it was broken, but it looks like it's just pagination "ending" (I assume?). I'd keep the pagination links in there. I was certain it had broken at first.

**Comment by cfjedimaster** [comment]
Yeah, the more I see this the more it feels wrong. For ex, I did `wsk activation list`, got 10 items plus pagination, click next, and I get one item. So... 11 items total?

**Comment by starpit** [comment]
this is due to the API not (yet) supporting a `count` attribute, so we don't know how many pages there are; this should change very soon, as the backend will soon support a count attribute on list calls.

opening a feature against the shell
