### ISSUE TITLE
Session flow fails to render for an app

### ISSUE THREAD

**Issue by cfjedimaster** [ibm-functions/composer#31]
I ran `session list`, clicked to view a session, and then clicked Session Flow. I got:

```
The flow visualization cannot be created because the app has been deleted. 

Visit the Trace tab to view a list of activations caused by the session.
```

However, the app is very much not deleted. This is an cron based trigger that runs every 15 minutes or so.

Session ID: 9bececaffa174569acecaffa17856983
App name: fshdottweet

**Comment by cfjedimaster** [comment]
FYI, the app name is really serverless_superman/fshdotweet. I also get an error if I run `app list` and click the name. If I click on any other name, all in the "root" package, it works.

**Comment by starpit** [comment]
moved to https://github.com/ibm-functions/shell/issues/294
