### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pdhoward** [ibm-functions/composer#33]
I am very excited to see this set of capability from IBM. Excellent development for the conversational worl

I hoping you can answer this before I invest too much time in testing discover the it will not work

Your docs state that the FSM "consists of a finite sequence of states starting with the initial state." Can I start the process at a later state if needed?

**Comment by tardieu** [comment]
Yes it is possible to start from an arbitrary state by changing the `Entry` field of the json-encoded FSM at invocation time, or by specifying the desired entry state as an additional `$state` parameter to the invocation.

**Comment by pdhoward** [comment]
Excellent! Thank you!
