### ISSUE TITLE
Loading indictators

### ISSUE THREAD

**Issue by cfjedimaster** [ibm-functions/composer#9]
I'm testing stuff at an airport with slow wifi and there is significant lag going from one thing to another. With no loading indicators, it appears as if things are broken. I'd add loading indicators pretty much everywhere.

**Comment by rabbah** [comment]
Issue moved to [ibm-functions/shell #41](https://github.com/ibm-functions/shell/issues/41) via [**ZenHub**](https://www.zenhub.com/)
